import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import { Poppins as PoppinsFont } from "next/font/google";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import { SessionProvider } from "@/components/provider/SessionProvider";

const poppins = PoppinsFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "EZ RETURNS",
  description: "Generated by create next app",
  icons: {
    icon: "/image/fav.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextTopLoader color="#31B8FA" height={3} showSpinner={false} />
        <ReactQueryProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReactQueryProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
